development:
  dialect: mysql
  database: loan_service_development
  user: root
  password: root@123
  host: 127.0.0.1
  port: 3306
  pool: 5

test:
  dialect: mysql
  database: loan_service_test
  user: root
  password: root@123
  host: 127.0.0.1
  port: 3306
  pool: 5

production:
  dialect: mysql
  database: loan_service_production
  user: root
  password: root@123
  host: 127.0.0.1
  port: 3306
  pool: 5