development:
  dialect: mysql
  database: lsd
  user: root
  password: root@123
  host: 127.0.0.1
  port: 3306
  pool: 5

test:
  dialect: mysql
  database: lsd
  user: root
  password: root@123
  host: db
  port: 3306
  pool: 5

production:
  dialect: mysql
  database: lsd
  user: root
  password: root@123
  host: db
  port: 3306
  pool: 5