DROP TABLE IF EXISTS kyc_histories;
DROP TABLE IF EXISTS loan_state_histories;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS investments;
DROP TABLE IF EXISTS loans;
DROP TABLE IF EXISTS investors;
DROP TABLE IF EXISTS borrowers;
DROP TABLE IF EXISTS employees; 