DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS loan_state_history;
DROP TABLE IF EXISTS investments;
DROP TABLE IF EXISTS loans;
DROP TABLE IF EXISTS investors;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS borrowers; 